/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zehra
 */
public class tas_kagit_makas extends javax.swing.JFrame {

    /**
     * Creates new form tas_kagit_makas
     */
    public tas_kagit_makas() {
        initComponents();
        panel_oyun_alanı.setVisible(false);
        panel_skor_alani.setVisible(false);
        
    }
    String ad = "";
    int oyuncuSkor = 0, bilgisayarSkor = 0, oyuncu = 0, bilgisayar = 0;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_oyuncu_bilgi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textfield_oyuncu_adi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panel_oyun_alanı = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton_Oyna = new javax.swing.JButton();
        button_resim_bilgisayar = new javax.swing.JButton();
        jComboBox_secim = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBox_bilgisayar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel_skor_durumu = new javax.swing.JLabel();
        button_resim_oyuncu = new javax.swing.JButton();
        panel_skor_alani = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_oyuncu_ad = new javax.swing.JLabel();
        jButton_yeni_oyun = new javax.swing.JButton();
        jLabel_oyuncu_skor = new javax.swing.JLabel();
        bilgisayar_puan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_oyuncu_bilgi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Oyuncu Adi");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Basla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textfield_oyuncu_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_oyuncu_adiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Oyuncu Bilgileri");

        javax.swing.GroupLayout panel_oyuncu_bilgiLayout = new javax.swing.GroupLayout(panel_oyuncu_bilgi);
        panel_oyuncu_bilgi.setLayout(panel_oyuncu_bilgiLayout);
        panel_oyuncu_bilgiLayout.setHorizontalGroup(
            panel_oyuncu_bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_oyuncu_bilgiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_oyuncu_bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_oyuncu_bilgiLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_oyuncu_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_oyuncu_bilgiLayout.setVerticalGroup(
            panel_oyuncu_bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_oyuncu_bilgiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panel_oyuncu_bilgiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_oyuncu_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panel_oyun_alanı.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Oyun Alanı");

        jButton_Oyna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Oyna.setText("Oyna");

        button_resim_bilgisayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resim_bilgisayarActionPerformed(evt);
            }
        });

        jComboBox_secim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_secim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TAŞ", "KAGIT", "MAKAS", " " }));
        jComboBox_secim.setSelectedIndex(-1);
        jComboBox_secim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_secimİtemStateChanged(evt);
            }
        });
        jComboBox_secim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_secimActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Oyuncunun Seçimi");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bilgisayarın Seçimi");

        comboBox_bilgisayar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboBox_bilgisayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 153));
        jLabel9.setText("Durum");

        jLabel_skor_durumu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_skor_durumu.setForeground(new java.awt.Color(153, 0, 153));
        jLabel_skor_durumu.setText("Bilgisayar kazandı");

        javax.swing.GroupLayout panel_oyun_alanıLayout = new javax.swing.GroupLayout(panel_oyun_alanı);
        panel_oyun_alanı.setLayout(panel_oyun_alanıLayout);
        panel_oyun_alanıLayout.setHorizontalGroup(
            panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_resim_oyuncu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                                .addComponent(jComboBox_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addComponent(jButton_Oyna, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(button_resim_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                        .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_skor_durumu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_oyun_alanıLayout.setVerticalGroup(
            panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_oyun_alanıLayout.createSequentialGroup()
                        .addComponent(jComboBox_secim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_Oyna, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_resim_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button_resim_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboBox_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panel_oyun_alanıLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_skor_durumu))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panel_skor_alani.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Skorlar");

        jLabel4.setText("Bilgisayar");

        jLabel_oyuncu_ad.setText("Oyuncu");

        jButton_yeni_oyun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_yeni_oyun.setForeground(new java.awt.Color(51, 153, 0));
        jButton_yeni_oyun.setText("Yeni Oyun");

        jLabel_oyuncu_skor.setText("0");
        jLabel_oyuncu_skor.setToolTipText("");

        bilgisayar_puan.setText("0");
        bilgisayar_puan.setToolTipText("");

        javax.swing.GroupLayout panel_skor_alaniLayout = new javax.swing.GroupLayout(panel_skor_alani);
        panel_skor_alani.setLayout(panel_skor_alaniLayout);
        panel_skor_alaniLayout.setHorizontalGroup(
            panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_skor_alaniLayout.createSequentialGroup()
                .addGroup(panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_skor_alaniLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_oyuncu_ad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bilgisayar_puan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_oyuncu_skor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_skor_alaniLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton_yeni_oyun)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panel_skor_alaniLayout.setVerticalGroup(
            panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_skor_alaniLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_oyuncu_ad)
                    .addComponent(jLabel_oyuncu_skor))
                .addGap(18, 18, 18)
                .addGroup(panel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bilgisayar_puan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_yeni_oyun, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_oyuncu_bilgi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_oyun_alanı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_skor_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_skor_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_oyuncu_bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panel_oyun_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_oyuncu_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_oyuncu_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_oyuncu_adiActionPerformed

    private void button_resim_bilgisayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resim_bilgisayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_resim_bilgisayarActionPerformed

    private void jComboBox_secimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_secimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_secimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ad= textfield_oyuncu_adi.getText();
        textfield_oyuncu_adi.setEnabled(false);
        panel_oyuncu_bilgi.setEnabled(false);
        panel_oyun_alanı.setVisible(true);
        panel_skor_alani.setVisible(true);
        jLabel_oyuncu_ad.setText(ad);
        jButton1.setEnabled(false);
        
        button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskagitmakas_resim/bos.png")));
        button_resim_bilgisayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskagitmakas_resim/bos.png")));
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_secimİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_secimİtemStateChanged
        if(String.valueOf(jComboBox_secim.getSelectedItem())== "TAŞ"){
            button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskagitmakas_resim/tas.png")));
        }else if(String.valueOf(jComboBox_secim.getSelectedItem())=="KAGIT")
            button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskagitmakas_resim/kagit.png")));
        else if(String.valueOf(jComboBox_secim.getSelectedItem())=="MAKAS"){
            button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskagitmakas_resim/makas.png")));
        } 
    }//GEN-LAST:event_jComboBox_secimİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tas_kagit_makas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bilgisayar_puan;
    private javax.swing.JButton button_resim_bilgisayar;
    private javax.swing.JButton button_resim_oyuncu;
    private javax.swing.JComboBox<String> comboBox_bilgisayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Oyna;
    private javax.swing.JButton jButton_yeni_oyun;
    private javax.swing.JComboBox<String> jComboBox_secim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_oyuncu_ad;
    private javax.swing.JLabel jLabel_oyuncu_skor;
    private javax.swing.JLabel jLabel_skor_durumu;
    private javax.swing.JPanel panel_oyun_alanı;
    private javax.swing.JPanel panel_oyuncu_bilgi;
    private javax.swing.JPanel panel_skor_alani;
    private javax.swing.JTextField textfield_oyuncu_adi;
    // End of variables declaration//GEN-END:variables
}
