/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dosyaıslemleri;

import java.io.*;
import java.nio.*;
import java.nio.charset.Charset;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Zehra
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        dosyaAc = new javax.swing.JButton();
        dosyadanKarakterOku = new javax.swing.JButton();
        DosyadanByteOku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DosyayaKarakterYaz = new javax.swing.JButton();
        DosyayaYenidenKarakterYaz = new javax.swing.JButton();
        dosyayaByteYaz = new javax.swing.JButton();
        dosyayaYenidenByteYaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dosyaAc.setText("Dosya Ac");
        dosyaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaAcActionPerformed(evt);
            }
        });

        dosyadanKarakterOku.setText("Dosyadan Karakter oku");
        dosyadanKarakterOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyadanKarakterOkuActionPerformed(evt);
            }
        });

        DosyadanByteOku.setText("Dosya byte oku");
        DosyadanByteOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosyadanByteOkuActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        DosyayaKarakterYaz.setText("Dosyaya karakter yaz");
        DosyayaKarakterYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosyayaKarakterYazActionPerformed(evt);
            }
        });

        DosyayaYenidenKarakterYaz.setText("Dosyaya Karakter Yeniden yaz ");
        DosyayaYenidenKarakterYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosyayaYenidenKarakterYazActionPerformed(evt);
            }
        });

        dosyayaByteYaz.setText("Dosyaya Byte Yaz");
        dosyayaByteYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyayaByteYazActionPerformed(evt);
            }
        });

        dosyayaYenidenByteYaz.setText("Dosyaya Byte Yeniden Yaz");
        dosyayaYenidenByteYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyayaYenidenByteYazActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dosyaAc)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dosyayaByteYaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DosyayaKarakterYaz, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DosyayaYenidenKarakterYaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dosyayaYenidenByteYaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dosyadanKarakterOku)
                                .addGap(45, 45, 45)
                                .addComponent(DosyadanByteOku, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(dosyaAc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosyadanKarakterOku)
                    .addComponent(DosyadanByteOku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DosyayaYenidenKarakterYaz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosyayaYenidenByteYaz))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DosyayaKarakterYaz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dosyayaByteYaz)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dosyaAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaAcActionPerformed
        // seçilen dosyanın path bilgisi ekrana yazdırılır
        jFileChooser1.setCurrentDirectory(new File(".\\src"));
        int i  =jFileChooser1.showOpenDialog(this);
        if(i == JFileChooser.APPROVE_OPTION){
            jTextArea1.append(jFileChooser1.getSelectedFile().getAbsolutePath() + "\n\n");
        }else{
            jTextArea1.append("Dosya açma işlemi iptal edildi");
        }
    }//GEN-LAST:event_dosyaAcActionPerformed

    private void DosyayaYenidenKarakterYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosyayaYenidenKarakterYazActionPerformed
        if(jFileChooser1.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            try{
                FileWriter wr = new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(),false);
                String[] satirlar = jTextArea1.getText().split("\n");
                for(int i = 0; i <satirlar.length ; i++){
                    wr.write(satirlar[i] +"\t\n");
                }
                wr.close();
                JOptionPane.showMessageDialog(this,"Dosyaya Yazıldı " , "", JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }    
    }//GEN-LAST:event_DosyayaYenidenKarakterYazActionPerformed

    private void dosyadanKarakterOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyadanKarakterOkuActionPerformed
        //seçilen dosyanın içeriği textArea'ya yazılır
        
        if(jFileChooser1.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            try{
                jTextArea1.setText("");
                FileReader fr = new FileReader(jFileChooser1.getSelectedFile().getAbsolutePath());
                BufferedReader br = new BufferedReader(fr);
                String line = br.readLine();
                while(line!= null){
                    jTextArea1.append(line + "\n");
                    line = br.readLine();
                }
                jTextArea1.append("\n");
                br.close();
            }catch(IOException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        }
        else{
            System.out.println("işlem yapmadan çıktınız");
        }
        
    }//GEN-LAST:event_dosyadanKarakterOkuActionPerformed

    private void DosyadanByteOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosyadanByteOkuActionPerformed
        if(jFileChooser1.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            try{
                jTextArea1.setText("");
                FileInputStream fis = new FileInputStream(jFileChooser1.getSelectedFile().getAbsoluteFile());
                InputStreamReader isr = new InputStreamReader(fis, Charset.forName("ISO-8859-9"));
                BufferedReader br = new BufferedReader(isr);
                String line = br.readLine();
                while(line!=null){
                 jTextArea1.append(line + "\n");
                 line = br.readLine();
                }    
                jTextArea1.append("\n");
                br.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }//GEN-LAST:event_DosyadanByteOkuActionPerformed

    private void DosyayaKarakterYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosyayaKarakterYazActionPerformed
        if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            try{
                FileWriter wr = new FileWriter(jFileChooser1.getSelectedFile().getAbsolutePath(),true);
                String [] satirlar = jTextArea1.getText().split("\n");
                for(int i = 0; i<satirlar.length ; i++ ){
                    wr.write(satirlar[i] + "\n");
                }
                wr.close();
                JOptionPane.showMessageDialog(this,"dosyaya yazıldı" , "" ,JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }//GEN-LAST:event_DosyayaKarakterYazActionPerformed

    private void dosyayaByteYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyayaByteYazActionPerformed
        if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            try{
                FileOutputStream fos = new FileOutputStream(jFileChooser1.getSelectedFile().getAbsolutePath(),true );
                OutputStreamWriter osr = new OutputStreamWriter(fos, Charset.forName("ISO-8859-9"));
                BufferedWriter bw = new BufferedWriter(osr);
                String[] satirlar = jTextArea1.getText().split("\n");
                for(int i=0 ; i<satirlar.length; i++){
                    bw.write(satirlar[i] + "\n");
                }
                bw.close();
                JOptionPane.showMessageDialog(null,"Dosyaya Yazıldı","",JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex){
                JOptionPane.showMessageDialog(this,ex.getMessage());
            }
        }
    }//GEN-LAST:event_dosyayaByteYazActionPerformed

    private void dosyayaYenidenByteYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyayaYenidenByteYazActionPerformed
        if(jFileChooser1.showSaveDialog(this)== JFileChooser.APPROVE_OPTION){
            try{
                FileOutputStream fr = new FileOutputStream(jFileChooser1.getSelectedFile().getAbsolutePath(),false);
                OutputStreamWriter osr = new OutputStreamWriter(fr, Charset.forName("ISO-8859-9"));
                String[] satirlar = jTextArea1.getText().split("\n");
                for(int i = 0; i <satirlar.length ; i ++){
                    osr.write(satirlar[i] + "\n" );
                }
                osr.close();
                JOptionPane.showMessageDialog(null,"Dosyaya Yazıldı","",JOptionPane.INFORMATION_MESSAGE);
            }catch(IOException ex ){
                JOptionPane.showMessageDialog(this,ex.getMessage());
            } 
        }
    }//GEN-LAST:event_dosyayaYenidenByteYazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DosyadanByteOku;
    private javax.swing.JButton DosyayaKarakterYaz;
    private javax.swing.JButton DosyayaYenidenKarakterYaz;
    private javax.swing.JButton dosyaAc;
    private javax.swing.JButton dosyadanKarakterOku;
    private javax.swing.JButton dosyayaByteYaz;
    private javax.swing.JButton dosyayaYenidenByteYaz;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
